### ISSUE TITLE
I get an error that train.txt isn't found

### ISSUE THREAD

**Issue by UsernameNotFound403** [Zhihan1996/TradeTheEvent#3]
`Traceback (most recent call last):
  File "run_domainadapt.py", line 300, in <module>
    main()
  File "run_domainadapt.py", line 229, in main
    get_dataset(data_args, tokenizer=tokenizer, cache_dir=model_args.cache_dir) if training_args.do_train else None
  File "run_domainadapt.py", line 125, in get_dataset
    return TextDataset(
  File "/Users/test/Downloads/TradeTheEvent-main/venv/lib/python3.8/site-packages/transformers/data/datasets/language_modeling.py", line 30, in __init__
    assert os.path.isfile(file_path), f"Input file path {file_path} not found"
AssertionError: Input file path DIR_TO_EDT_DATASET/Domain_adaptation/train.txt not found
`
Do i have to download additional files for this project from somewhere or why do I get this error

**Comment by Zhihan1996** [comment]
Hi,

Yes. You need to download the dataset from https://drive.google.com/drive/folders/1xKjd9hzA8UTn2DXVIYYnX5TngNAMom19 and set the Environment variable DIR_TO_EDT_DATASET and the directory of this dataset.
